# Generated by Django 3.2.9 on 2021-12-05 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nftdata',
            unique_together={('contract_address', 'token_id')},
        ),
    ]
